# Generated by Django 5.1.1 on 2024-10-28 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
